# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- refs/tags/*

jobs:
  - job: test_lint
    displayName: "Run tests, fmt, and clippy"
    steps:
      - template: ci/azure-install-rust.yml
      - script: cargo test --locked
        displayName: "cargo test --locked"
      - script: cargo fmt --all -- --check
        displayName: "cargo fmt"
      - script: cargo clippy
        displayName: "cargo clippy"

  - job: test_lint_windows
    displayName: "Run tests (Windows)"
    pool:
      vmImage: vs2017-win2016
    steps:
      - template: ci/azure-install-rust.yml
      - script: cargo test --locked
        displayName: "cargo test --locked"

  - job: test_lint_nightly
    displayName: "Run tests (nightly)"
    steps:
      - template: ci/azure-install-rust.yml
        parameters:
          toolchain: nightly
      - script: cargo test --locked

displayName: "cargo test --locked"
