[workspace]
resolver = "2"
members = [
    "delete-line",
    "delete-local-branches",
    "aws-flow-logs",
    "aws-ssm-env-importer",
    "aws-ssm-env-exporter",
    "aws-logs-utils",
    "uuid-gen",
]
