[workspace]
members = [
    "delete-line",
    "delete-local-branches",
    "aws-flow-logs",
    "aws-ssm-env-importer",
    "aws-ssm-env-exporter",
    "fix-ksql-deleted-topics",
    "aws-logs-utils",
]
