[package]
name = "aws-ssm-env-importer"
version = "0.2.1"
authors = ["Jayson Reis <santosdosreis@gmail.com>"]
edition = "2018"

[dependencies]
clap = { version = "4.5.43", features = ["derive", "env"] }
color-eyre = "0.6.5"
envfile = "0.2.1"
lazy_static = "1.5.0"
log = "0.4.27"
r2d2 = "0.8.10"
rayon = "1.10.0"
rusoto_core = "0.48.0"
rusoto_ssm = "0.48.0"
tokio = { version = "1.47.1", features = ["rt-multi-thread", "macros", "fs"] }
