[package]
name = "delete-local-branches"
version = "0.2.1"
authors = ["Jayson Reis <santosdosreis@gmail.com>"]
edition = "2018"

[dependencies]
color-eyre = "0.6.2"
env_logger = "0.10.0"
git2 = "0.16.1"
log = "0.4.6"
