[package]
name = "aws-flow-logs"
version = "0.2.1"
authors = ["Jayson Reis <santosdosreis@gmail.com>"]
edition = "2018"

[dependencies]
aws-logs-utils = { path = "../aws-logs-utils" }
clap = { version = "4.5.43", features = ["derive", "env"] }
color-eyre = "0.6.5"
env_logger = "0.11.8"
lazy_static = "1.5.0"
rusoto_core = "0.48.0"
rusoto_s3 = "0.48.0"
tokio = { version = "1.47.1", features = ["rt-multi-thread", "macros"] }
